/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_chenlijun99_jetbrainsassignment_zstd_Zstd */

#ifndef _Included_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
#define _Included_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    compress
 * Signature: ([B[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_compress
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    compressCritical
 * Signature: ([B[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_compressCritical
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    getCompressBound
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_getCompressBound
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    isError
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_isError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    getErrorName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_getErrorName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    getErrorCode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_getErrorCode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errNoError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errNoError
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errGeneric
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errGeneric
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errPrefixUnknown
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errPrefixUnknown
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errVersionUnsupported
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errVersionUnsupported
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errFrameParameterUnsupported
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errFrameParameterUnsupported
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errFrameParameterWindowTooLarge
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errFrameParameterWindowTooLarge
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errCorruptionDetected
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errCorruptionDetected
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errChecksumWrong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errChecksumWrong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errDictionaryCorrupted
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errDictionaryCorrupted
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errDictionaryWrong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errDictionaryWrong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errDictionaryCreationFailed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errDictionaryCreationFailed
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errParameterUnsupported
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errParameterUnsupported
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errParameterOutOfBound
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errParameterOutOfBound
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errTableLogTooLarge
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errTableLogTooLarge
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errMaxSymbolValueTooLarge
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errMaxSymbolValueTooLarge
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errMaxSymbolValueTooSmall
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errMaxSymbolValueTooSmall
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errStageWrong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errStageWrong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errInitMissing
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errInitMissing
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errMemoryAllocation
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errMemoryAllocation
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errWorkSpaceTooSmall
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errWorkSpaceTooSmall
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errDstSizeTooSmall
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errDstSizeTooSmall
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errSrcSizeWrong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errSrcSizeWrong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_chenlijun99_jetbrainsassignment_zstd_Zstd
 * Method:    errDstBufferNull
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_chenlijun99_jetbrainsassignment_zstd_Zstd_errDstBufferNull
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
